POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlkYSIsImlkIjoiNjNlMjVlYTg5NzBlMjhiODBlZDE5Zjc0IiwiaWF0IjoxNjc1ODY2MzQwfQ.AjPSSBEGsd9xmvC8qtWepoLkYyUlrER6YGzgQH0LEdU

{
  "title": "idan voittaja testi",
  "author": "toinen kirjoittaja",
  "url": "toinenblogi.com"
}