PUT http://localhost:3003/api/blogs/63d91d813ecd0c25ccfd93a9
Content-Type: application/json

{
"title": "uusi blogi",
"author": "Maria",
"url": "www.marianblogi.fi",
"likes": 314,
"id": "63d91d813ecd0c25ccfd93a9"
}